/*
 * Promotion types.
 */
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const ADD_PROMOTION_ACTIVATED = 'ADD_PROMOTION_ACTIVATED';
export const ADD_PROMOTION_ACTIVATING = 'ADD_PROMOTION_ACTIVATING';
export const ADD_PROMOTION_ADDING = 'ADD_PROMOTION_ADDING';
export const ADD_PROMOTION_ERROR = 'ADD_PROMOTION_ERROR';
export const ADD_SINGLE_PROMOTION = 'ADD_SINGLE_PROMOTION';

/*
 * Session types.
 */
export const ADD_SESSION = 'ADD_SESSION';
export const ADD_SESSION_ADDING = 'ADD_SESSION_ADDING';
export const ADD_SESSION_ENDING = 'ADD_SESSION_ENDING';
export const ADD_SESSION_ERROR = 'ADD_SESSION_ERROR';
export const ADD_SESSION_HISTORY = 'ADD_SESSION_HISTORY';
export const ADD_SESSION_HISTORY_ADDING = 'ADD_SESSION_HISTORY_ADDING';
export const ADD_SESSION_HISTORY_ERROR = 'ADD_SESSION_HISTORY_ERROR';
export const END_SESSION = 'END_SESSION';
export const REMOVE_SESSION_ENDING_COMPLETED = 'REMOVE_SESSION_ENDING_COMPLETED';
export const UPDATE_SESSIONS = 'UPDATE_SESSIONS';

/*
 * User types.
 */
export const ADD_CARD = 'ADD_CARD';
export const ADD_CARDS = 'ADD_CARDS';
export const ADD_CARD_ADDING = 'ADD_CARD_ADDING';
export const ADD_CARD_ERROR = 'ADD_CARD_ERROR';
export const ADD_CARD_REMOVING = 'ADD_CARD_REMOVING';
export const ADD_CARD_SELECTING = 'ADD_CARD_SELECTING';
export const ADD_DEVICE_TOKEN_ADDING = 'ADD_DEVICE_TOKEN_ADDING';
export const ADD_DEVICE_TOKEN_ENDING = 'ADD_DEVICE_TOKEN_ENDING';
export const ADD_STRIPE_ID_WITH_CARD = 'ADD_STRIPE_ID';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_NAME_CHANGING = 'ADD_USER_NAME_CHANGING';
export const ADD_USER_SIGNING_IN = 'ADD_USER_SIGNING_IN';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const LOG_OUT = 'LOG_OUT';
export const REMOVE_CARD = 'REMOVE_CARD';
export const SELECT_CARD = 'SELECT_CARD';
